/**
 * Vercel build step for the demo deployment.
 *
 * Builds a fresh, migrated and seeded SQLite database and embeds it into
 * src/demo/snapshot.ts as base64. At runtime every serverless instance
 * restores the same snapshot into /tmp, so seeded IDs (and therefore sessions)
 * are identical across instances. Data written on the live site is not
 * durable — it lives only as long as the instance that handled it.
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const dbFile = path.resolve("prisma/demo-build.db");
fs.rmSync(dbFile, { force: true });

const env = {
  ...process.env,
  DATABASE_URL: `file:${dbFile}`,
  RF_BUILDING: "1",
  ALLOW_DEMO_SEED: "true",
  STORAGE_DIR: path.resolve(".demo-build-storage"),
};

execSync("npx prisma migrate deploy", { env, stdio: "inherit" });
execSync("npx tsx prisma/seed.ts", { env, stdio: "inherit" });

const b64 = fs.readFileSync(dbFile).toString("base64");
fs.writeFileSync(
  "src/demo/snapshot.ts",
  `// Generated by scripts/build-demo-db.ts at build time. Do not edit.\nexport const DEMO_DB_BASE64 = ${JSON.stringify(b64)};\n`,
);
fs.rmSync(dbFile, { force: true });
console.log(`Embedded demo database (${Math.round(b64.length / 1024)} KB base64)`);
